name: Build Kivy APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git zip unzip openjdk-17-jdk python3-pip automake autoconf libtool
        pip install --upgrade pip
        pip install Cython==0.29.36 virtualenv
        git clone https://github.com/kivy/buildozer.git
        cd buildozer && sudo python3 setup.py install
        cd ..

    - name: Install specific Android build-tools
      run: |
        yes | sdkmanager "build-tools;33.0.2"
        ls $ANDROID_HOME/build-tools

    - name: Configure buildozer.spec
      run: |
        buildozer init || true
        sed -i 's/^requirements = .*/requirements = python3,kivy==2.2.1,requests/' buildozer.spec
        sed -i 's/^# source.include_exts =.*/source.include_exts = py,json/' buildozer.spec
        sed -i 's/^# android.api =.*/android.api = 31/' buildozer.spec
        sed -i 's/^# android.ndk =.*/android.ndk = 25b/' buildozer.spec
        sed -i 's/^# android.archs =.*/android.archs = arm64-v8a/' buildozer.spec
        echo "android.build_tools_version = 33.0.2" >> buildozer.spec

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-kivy-apk
        path: bin/*.apk
